Rails:
  Enabled: true

Metrics/LineLength:
  Max: 256

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*' # piplines vendor cache
  TargetRubyVersion: 2.5
